// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8787' | (string & {});
};

export type GetApiHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetApiHealthErrors = {
    /**
     * 内部サーバーエラー（予期しないエラーが発生した場合）
     */
    500: {
        error: string;
        /**
         * 統一エラーコード: NET_xxx(ネットワーク), SVR_xxx(サーバー), VAL_xxx(バリデーション), AUTH_xxx(認証), UNK_xxx(不明)
         */
        errorCode: 'NET_001' | 'NET_002' | 'NET_003' | 'NET_004' | 'SVR_001' | 'SVR_002' | 'SVR_003' | 'SVR_004' | 'SVR_005' | 'VAL_001' | 'VAL_002' | 'VAL_003' | 'VAL_004' | 'AUTH_001' | 'AUTH_002' | 'AUTH_003' | 'AUTH_004' | 'UNK_001' | 'UNK_002' | 'UNK_003' | 'UNK_004';
        timestamp: string;
    };
    /**
     * サービス利用不可エラー（ヘルスチェックが失敗した場合）
     */
    503: {
        error: string;
        /**
         * 統一エラーコード: NET_xxx(ネットワーク), SVR_xxx(サーバー), VAL_xxx(バリデーション), AUTH_xxx(認証), UNK_xxx(不明)
         */
        errorCode: 'NET_001' | 'NET_002' | 'NET_003' | 'NET_004' | 'SVR_001' | 'SVR_002' | 'SVR_003' | 'SVR_004' | 'SVR_005' | 'VAL_001' | 'VAL_002' | 'VAL_003' | 'VAL_004' | 'AUTH_001' | 'AUTH_002' | 'AUTH_003' | 'AUTH_004' | 'UNK_001' | 'UNK_002' | 'UNK_003' | 'UNK_004';
        timestamp: string;
    };
};

export type GetApiHealthError = GetApiHealthErrors[keyof GetApiHealthErrors];

export type GetApiHealthResponses = {
    /**
     * システムの稼働状況とISO形式のタイムスタンプを含むJSONオブジェクトを返却
     */
    200: {
        status: string;
        timestamp: string;
    };
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];
