name: 'Node Install'
description: 'Setup Node.js and install dependencies'

inputs:
  pnpm-version:
    description: 'The version of pnpm to install'
    required: false
    default: 10.24.0
  node-version:
    description: 'The version of Node.js to use'
    required: false
    default: 24.11.1

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Set Node.js version to ${{ inputs.node-version }}
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        HUSKY: '0'
